name: lint-check

on:
  pull_request:
    branches:
      - main

jobs:
  check-main-commit:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4
        
          
          
      - name: lint
        run: |
          npm i -g pnpm
          pnpm i
          pnpm lint